parallel-jobs = 1
enable-magisk-update = true

[Black-rv]
enabled = true
app-name = "blaack"
cli-source = "j-hc/revanced-cli"
build-mode = "apk"
rv-brand = "rv"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black --rip-lib armeabi-v7a"
riplib = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Change version code' 'Enable slide to seek'"
excluded-patches = "'Theme''Change header' 'Custom branding' 'Alternative thumbnails' 'Return YouTube Dislike'"
apkmirror-arch = "arm64-v8a"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Dark-mp]
enabled = true
app-name = "daark"
cli-source = "MorpheApp/morphe-cli"
patches-source = "MorpheApp/morphe-patches"
#integrations-source = "MorpheApp/morphe-integrations"
build-mode = "apk"
riplib = true
rv-brand = "mp"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF1F1F1F -e 'Custom branding' -OcustomName='YouTube X'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Custom branding' 'Change version code' 'Enable slide to seek'"
excluded-patches = "'XTheme' 'Change header' 'XCustom branding' 'Alternative thumbnails' 'Return YouTube Dislike'"
apkmirror-arch = "arm64-v8a"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"


[Black-mp]
enabled = true
app-name = "blaack"
cli-source = "MorpheApp/morphe-cli"
patches-source = "MorpheApp/morphe-patches"
#integrations-source = "MorpheApp/morphe-integrations"
build-mode = "apk"
riplib = true
rv-brand = "mp"
patcher-args = "-e 'Custom branding' -OcustomName='YouTube X'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Custom branding' 'Change version code' 'Enable slide to seek'"
excluded-patches = "'Theme' 'Change header' 'XCustom branding' 'Alternative thumbnails' 'Return YouTube Dislike'"
apkmirror-arch = "arm64-v8a"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Dark-rv]
enabled = false
app-name = "daark"
cli-source = "j-hc/revanced-cli"
build-mode = "both"
rv-brand = "rv"
riplib = true
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF1F1F1F --rip-lib armeabi-v7a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Change version code' 'Enable slide to seek'"
excluded-patches = "'Change header' 'Custom branding' 'Alternative thumbnails' 'Return YouTube Dislike'"
apkmirror-arch = "arm64-v8a"
#version = "19.16.39"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-rv]
enabled = false
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
excluded-patches = "'Change header' 'Custom branding' 'Alternative thumbnails' 'Return YouTube Dislike'"

[Boost-RV]
enabled = false
app-name = "Boost"
build-mode = "apk"
version = "auto"
rv-brand = "RV"
patcher-args = "-e 'Spoof client' -Oclient-id=e1toDqv8Jgg9wIqwcS71Eg "
apkmirror-dlurl = "https://www.apkmirror.com/apk/ruben-mayayo/boost-for-reddit/"

[GooglePhotos]
enabled = false
build-mode = "apk"
arch = "arm64-v8a"
version = "7.1.0.677535587"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"


[GoogleNews]
enabled = false
build-mode = "apk"
#arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
#uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[MyExpense]
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"
enabled = false

[Black-rvx]
enabled = true
app-name = "og-black"
patches-source = "anddea/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -e 'Custom branding icon for YouTube' -OappIcon=youtube -OrestoreOldSplashAnimation=true -e 'Custom branding name for YouTube' -OappName='YouTube X' --rip-lib armeabi-v7a"
apkmirror-arch = "arm64-v8a"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Change version code' 'Custom branding name for YouTube'"
excluded-patches = "'Custom branding icon forYouTube' 'Custom header for YouTube' 'Return YouTube Dislike' 'Alternative thumbnails'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Dark-rvx]
enabled = true
app-name = "og-dark"
patches-source = "anddea/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=#FF1F1F1F -e 'Custom branding icon for YouTube' -OappIcon=youtube -OrestoreOldSplashAnimation=true -e 'Custom branding name for YouTube' -OappName='YouTube X' --rip-lib armeabi-v7a"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Change version code' 'Custom branding name for YouTube'"
excluded-patches = "'Custom branding icon forYouTube' 'Custom header for YouTube' 'Return YouTube Dislike' 'Alternative thumbnails'"
#patches-version = "v5.1.1-dev.2"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-rvx]
enabled = false
app-name = "Music"
patches-source = "anddea/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "rvx"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"
#version="6.50.51"
include-stock = true
included-patches = "'Change version code'"
excluded-patches = "'Amoled' 'Change start page' 'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom package name' 'Return YouTube Dislike' 'Visual preferences icons for YouTube Music'"
