name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows you to manually trigger it whenever you want

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Sync fork with upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Replace 'main' with your default branch name if it's 'master'
        run: gh repo sync ${{ github.repository }} -b rvx
